### ISSUE TITLE
Remove pdf from git repo

### ISSUE THREAD

**Issue by grantwwu** [jvanburen/21-373-s16#10]
Binary files bloat the repo, making the download size larger, and make merging/rebasing difficult as git's conflict resolution doesn't really know what to do with the binary file.

I suggest some sort of continuous integration scheme that builds against HEAD using a git-hook.

**Comment by jvanburen** [comment]
specific suggestions?

**Comment by grantwwu** [comment]
Wait until Thursday when I'm no longer dying.

Most likely we'd want to set up some sort of CGI script to respond to a GitHub webhook request.

**Comment by jvanburen** [comment]
Beginning the process of setting up a build script on my desktop later tonight (hopefully)

**Comment by jvanburen** [comment]
Too hard for now, unless someone else wants to do it, adding wontfix
