### ISSUE TITLE
Index Fixing

### ISSUE THREAD

**Issue by jvanburen** [jvanburen/21-373-s16#7]
The index is not in correct alphabetic order.
Specifically, the `\kw{asdf}` macro needs fixing.

**Comment by grantwwu** [comment]
Referring to http://tex.stackexchange.com/questions/215967/formated-text-in-acronym-sorted-alphabetically-in-index I believe the best way to fix this is to use xindy instead.

**Comment by jvanburen** [comment]
Fixed by commit `d415978`
